<a href="https://colab.research.google.com/github/tripathiosho/ImportantNotebooks/blob/main/Copy_of_NN_Forward_and_backward_Propogation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

!gdown 1dLOPwh01o3k8p_hK633ixhD1ehz6nNWk
df = pd.read_csv("/content/spiral.csv")
df.head()

Downloading...
From: https://drive.google.com/uc?id=1dLOPwh01o3k8p_hK633ixhD1ehz6nNWk
To: /content/spiral.csv
100% 12.9k/12.9k [00:00<00:00, 4.71MB/s]


,x1,x2,y
0,0.000000,0.000000,0
1,-0.000650,0.010080,0
2,0.009809,0.017661,0
3,0.007487,0.029364,0
4,-0.000027,0.040404,0


In [ ]:
df.shape

(300, 3)

In [ ]:
df['y'].value_counts()

,count
y,
0,100
1,100
2,100


In [ ]:
df['y'].unique()

array([0, 1, 2])

In [ ]:
# Separating feature and label columns
X = df.iloc[:, :-1].to_numpy()
y = df.iloc[:, -1].to_numpy()

In [ ]:
d= X.shape[1] #dimensions x1, x2

In [ ]:
n= len(df['y'].unique()) #no. of classes
m= X.shape[0] #no. of examples

In [ ]:
w = 0.01 * np.random.randn(d,n)

In [ ]:
d

2

In [ ]:
w

array([[ 0.00846681, -0.01093009,  0.00749218],
       [-0.00905226,  0.00397925, -0.00126758]])

In [ ]:
b=np.zeros((1,n))

In [ ]:
b

array([[0., 0., 0.]])

In [ ]:
z = np.dot(X,w) + b

In [ ]:
z.shape

(300, 3)

In [ ]:
e_z = np.exp(z)
e_z / np.sum(e_z, axis=1, keepdims=True)

array([[0.33333333, 0.33333333, 0.33333333],
       [0.33330855, 0.33335654, 0.33333491],
       [0.33331469, 0.33332798, 0.33335733],
       [0.33328237, 0.33336151, 0.33335613],
       [0.33323983, 0.33341551, 0.33334467],
       [0.33323456, 0.33340366, 0.33336178],
       [0.33328096, 0.33331194, 0.3334071 ],
       [0.33323614, 0.33336388, 0.33339998],
       [0.33318637, 0.33342695, 0.33338668],
       [0.33323186, 0.33333595, 0.33343219],
       [0.33318025, 0.33339979, 0.33341997],
       [0.33316868, 0.3334004 , 0.33343092],
       [0.33316616, 0.33338659, 0.33344724],
       [0.3331058 , 0.33346655, 0.33342765],
       [0.33317861, 0.33333261, 0.33348879],
       [0.33325262, 0.33320626, 0.33354112],
       [0.33324188, 0.33320551, 0.33355261],
       [0.33330737, 0.333097  , 0.33359563],
       [0.33322377, 0.33319919, 0.33357705],
       [0.33337585, 0.33297253, 0.33365162],
       [0.3334101 , 0.33291158, 0.33367832],
       [0.33321644, 0.33316101, 0.33362255],
       [0.